const CAMPOS =
{
    CONSULTA:
    {
    EDITAR_REQUISICAO: '[ID$=vEDITAR_0001]', //vEDITAR_0001
    FILTRO_STATUS: '[ID$=vEST140STATUS]', //vEST140STATUS
    PESQUISAR_REQUISICAO: '[ID$=IMGPESQUISA]', //IMGPESQUISA
    },

    PROCESSO:
    {
    INICIAR_SEPARACAO: '[ID$=BTNSEPARACAOINICIAR]', //BTNSEPARACAOINICIAR
    CANCELAR_REQUISICAO: '[ID$=REQUISICAOCANCELAR]', //BTNREQUISICAOCANCELAR
    BOTAO_FECHAR: '[ID$=BTNFECHAR]', //BTNFECHAR
    CONFIRMAR_SEPARACAO: 'BTNENTER', //BTNENTER //'[ID$=BTNENTER]'
    POPUP_CONFIRMAR_SEPARACAO: '#gxp0_gxtitle', //#gxp0_gxtitle
    FECHAR_SEPARACAO: '[#BTNCANCEL]', //#BTNCANCEL
    AUTO_SEPARAR_ITENS: '[ID$=AUTOSEPARAR]', //#W0187BTNAUTOSEPARAR
    INFORMAR_TODOS: '[ID$=INFORMARTODOS]', //#W0187BTNINFORMARTODOS
    LER_CODIGO_BARRAS: '[ID$=LERCODIGOBARRAS]' , //#W0187BTNLERCODIGOBARRAS
    EDITAR_ITEM: '[ID$=vUPDATEREGISTRO]', //#W0187vUPDATEREGISTRO_0001
    ABA_ITENS: '[ID$=Tab_GXUITABSPANEL_TABSContainerpanel2]' , //Tab_GXUITABSPANEL_TABSContainerpanel2
    QUANTIDADE_SEPARACAO: '[ID$=QUANTIDADESEPARADA]', //#W0187W0059EST142QUANTIDADESEPARADA
    SALVAR_QUANTIDADE_SEPARACAO: '[ID$=TRN_ENTER]' , //#W0187W0059BTNTRN_ENTER
    FECHAR_QUANTIDADE_SEPARACAO: '[ID$=BTNFECHAR]', //#W0187W0059BTNFECHAR
    ABA_SEPARACAO_GUARDA: '[ID$=Tab_GXUITABSPANEL_TABSContainerpanel3]', //Tab_GXUITABSPANEL_TABSContainerpanel3
    FINALIZAR_ETAPA_ATUAL: '[ID$=ETAPAATUALFINALIZAR]' , //#W0195BTNETAPAATUALFINALIZAR
    SALVAR_SEPARACAO:'[ID$=#BTNTRN_ENTER]', //#BTNTRN_ENTER
    FLAG_ENTREGA_REALIZADA: 'vENTREGAR'
    },
    

}
export default CAMPOS;