const CAMPOS =
{
    CONSULTA:
    {
        BOTAO_INSERIR: '[ID$=INSERT]', //'#BTNBTNINSERT',
        LIMPAR_FILTRO: '[ID$=CLEANFILTERS]',
        CODINT_ORDEM_COMPRA: '#vVAR20PEDIDOID',//#vVAR20PEDIDOID
    },

    GERACAO:
    {
        WIZARD_1_ABERTURA:
        {
            PAINEL_GERAL: '#Title_W0021DVPANEL_UNNAMEDTABLE1Container',
            CLIENTE_ID: '#W0021W0020VAR20CLIENTEID', // [ID$=VAR20CLIENTEID
            ENDERECO_ID: '#W0021W0020VAR20CLIENTEENDERECOID', // [ID$=VAR20CLIENTEENDERECOID]
            VENDEDOR_ID: '#W0021W0020VAR20VENDEDORID', //[ID$=VAR20VENDEDORID]
            POLITICAPRAZO_ID: '#W0021W0020VAR20POLPRAZOID', // [ID$=VAR20POLPRAZOID]
            TABDESC_ID: '#W0021W0020VAR20DESCONTOID', //'[ID$=VAR20DESCONTOID]'
            PEDIDO_ID: '#W0021W0012vVAR20PEDIDOID', //'[ID$=vVAR20PEDIDOID]'
            PESQUISAR_PEDIDO: '#IMGPESQUISA',
            BOTAO_SEGUINTE: '[id$=BTNTRN_ENTER]', // W0021W0020BTNTRN_ENTER'
            ORDEM_COMPRA_ID: '[id$=vVAR20PEDIDOID]',//'W0021W0012vVAR20PEDIDOID'
    },
        WIZARD_2_ITENS:
        {
            ORDEM_COMPRA_ID: '[id$=vVAR20PEDIDOID]', //'W0021W0012vVAR20PEDIDOID'
            PESQUISAR: '[id$=ENTER]',
            EDITAR: '#vEDITAR_0001',
            COD_PRODUTO: '#W0021W0012vE18CODPRO',
            PESQUISAR_PRODUTO: '#W0021W0012ENTER', //'[id$=BTNTRN_ENTER]'
            PESQUISAR_ORDEM_COMPRA: '#IMGPESQUISA',
            BOTAO_SALVAR: '[id$=BTNTRN_ENTER]', //W0021W0012W0453BTNTRN_ENTER
            ADICIONAR_PROD: '#W0021W0012vADICIONAR_0001',
            VENDEDOR: '[id$=VENDEDORID]',//W0021W0012W0453VAR21VENDEDORID
            //TABLE_PRINCIPAL: '[id$=TABLEPRINCIPAL]',
            BOTAO_FECHAR_CARRINHO: '[id$=BTNWIZARDSEGUINTE]',
            MOTIVO_ALOCACAO: '[id$=vMOTIVO]', //W0021W0012W0453W0398vMOTIVO', campo motivo popup liberação alocação
            LIBERAR_ALOCACAO: '[id$=vLIBERAR]', //W0021W0012W0453W0398vLIBERAR, combobox liberar popup liberação alocação
            BOTAO_CONFIRMAR: '[id$=BTNENTER]', //W0021W0012W0453W0398BTNENTER botão confirmar popup liberação alocação
            QUANTIDADE: '[id$=QUANTIDADE]',//W0021W0012W0453VAR21QUANTIDADE
            PRECO_UNITARIO: '[id$=PRECOUNITARIO]', //W0021W0012W0453VAR21PRECOUNITARIO
            POPUP_BLOQUEIO: '[id$=TEXTBLOCKTITLE]',//W0021W0012W0453W0398TEXTBLOCKTITLE 
            BOTAO_OK: '[id$=BTNENTER]', //W0021W0012W0453W0398BTNENTER
            LUPA_ORDEM_COMPRA: '[id$=vCONSULTAR_0001]',//vCONSULTAR_0001
            ABA_TOTAIS: '[id$=Containerpanel2]',// Tab_GXUITABSPANEL_TABSPEDIDOContainerpanel2
            STATUS_BLOQUEIO: '#span_W0113VAR21STATUSBLOQUEIO_0001'//span_W0113VAR21STATUSBLOQUEIO_0001
            
        },

        WIZARD_3_OUTROS:
        {
            ORDEM_COMPRA_ID: '[id$=vVAR20PEDIDOID]',//'#W0021W0012vVAR20PEDIDOID',
            PESQUISAR_ORDEM_COMPRA: '#IMGPESQUISA',
            EDITAR: '#vEDITAR_0001',
            EDITAR_TOTAIS: '[id$=EDITARTOTAIS]',//'#W0021EDITARTOTAIS',
            BOTAO_SEGUINTE: '[id$=BTNWIZARDNEXT]'//'#W0021BTNWIZARDNEXT',
        },

        WIZARD_4_BLOQUEIOS:
        {
            ORDEM_COMPRA_ID: '[id$=vVAR20PEDIDOID]',//'#W0021W0012vVAR20PEDIDOID',
            PESQUISAR_ORDEM_COMPRA: '#IMGPESQUISA',
            EDITAR: '#vEDITAR_0001',
            EDITAR_TOTAIS: '[id$=EDITARTOTAIS]',//'#W0021EDITARTOTAIS',
            BOTAO_SEGUINTE: '[id$=BTNWIZARDNEXT]', //#W0021BTNWIZARDNEXT',

            BOTAO_ANTERIOR: '[id$=BTNWIZARDPREVIOUS]',//'#W0021BTNWIZARDPREVIOUS',
            BOTAO_SEGUINTE: '[id$=BTNWIZARDNEXT]'//'#W0021BTNWIZARDNEXT',
            
        },
        WIZARD_6_CONFIRMACAO:
        {
            ORDEM_COMPRA_ID: '[id$=vVAR20PEDIDOID]',//'#W0021W0012vVAR20PEDIDOID',
            PESQUISAR_ORDEM_COMPRA: '#IMGPESQUISA',
            EDITAR: '#vEDITAR_0001',
            GERAR_FATURA: '[id$=BTNEMITIRNF]'//'W0021W0015BTNEMITIRNF'

        },
        FATURA:
        {
            FATURA_ID: '[id$=vVAR30FATURAID]', //vVAR30FATURAID
            PEDIDO_ID: '[id$=PEDIDOID]', //vVAR30PEDIDOID     
            PESQUISAR_FATURA: '[id$=IMGPESQUISA]',//IMGPESQUISA  
            EDITAR_FATURA: '[id$=vEDITAR_0001]',//vEDITAR_0001
            BOTAO_EMITIR_NF: '#BTNENTER', //'#W0081BTNENTER', // cy.get('#BTNENTER')
            POPUP_NOTAFISCAL: 'W0404TEXTBLOCKTITLE', //[id$=TEXTBLOCKTITLE]
            BOTAO_OK_POPUP: 'W0404BTNENTER',//W0404BTNENTER
            BOTAO_HABILITAR_ALTERACAO: '[id$=BTNFATURAALTERACAO]',//BTNFATURAALTERACAO
            DATA_HORA: '[id$=SAIDADATAHORAPARM]'//vVAR30SAIDADATAHORAPARM
        }
}}

export default CAMPOS;